<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Magick.NET-Q16-AnyCPU" Version="14.16.0" />
    <ProjectReference Include="..\TwinCheck.Agent.Core\TwinCheck.Agent.Core.csproj" />
  </ItemGroup>

</Project>
